development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: feathers_development
  pool: 5
  username: feathers
  password: feathers

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: feathers_test
  pool: 5
  username: feathers
  password: feathers

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: feathers_production
  pool: 5
  username: feathers
  password: feathers
